'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowRight, BarChart3, CalendarDays, Check, ChevronDown, Clock3, Menu, MessageSquareText, ShieldCheck, Sparkles, Users, X, XCircle } from 'lucide-react'

type Reservation = { id:number; name:string; phone:string; date:string; time:string; party_size:number; status:string }
const slots = ['17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00']
const links = [['Product','product'],['For restaurants','restaurants'],['Stories','stories'],['Pricing','pricing']] as const
const faqs = [
  ['Can ReserveFlow prevent double bookings?','Yes. Live availability and capacity limits protect every service from overlapping reservations.'],
  ['Do guests need an account?','No. Guests reserve with their name and phone number and receive confirmation instantly.'],
  ['Can my team cancel a reservation?','Yes. Staff can cancel directly from the live list and the time becomes available again.'],
  ['Can the booking page match our brand?','Professional plans include a customizable booking experience for your restaurant.'],
]

export default function Home() {
  const today = new Date().toISOString().split('T')[0]
  const [open,setOpen] = useState(false), [faq,setFaq] = useState(0), [loading,setLoading] = useState(false)
  const [message,setMessage] = useState(''), [reservations,setReservations] = useState<Reservation[]>([])
  const [form,setForm] = useState({name:'',phone:'',date:today,time:'19:00',partySize:'2'})
  const load = async()=>{ try { const r=await fetch('/api/reservations',{cache:'no-store'}); if(r.ok)setReservations(await r.json()) } catch {} }
  useEffect(()=>{load()},[])
  const booked=useMemo(()=>new Set(reservations.filter(r=>r.date===form.date&&r.status==='confirmed').map(r=>r.time)),[reservations,form.date])
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{const r=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage('✓ Table reserved. Your confirmation is ready.');setForm(v=>({...v,name:'',phone:''}));await load()}catch(e){setMessage(e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)}}
  async function cancel(id:number){if((await fetch(`/api/reservations/${id}`,{method:'DELETE'})).ok)await load()}
  return <main className="overflow-hidden bg-white text-ink">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/15 bg-[#171817]/85 text-white backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo/><div className="hidden gap-8 text-sm md:flex">{links.map(([l,id])=><a key={id} href={`#${id}`} className="text-white/70 hover:text-white">{l}</a>)}</div><a href="#reserve" className="hidden rounded bg-brand px-5 py-3 text-sm font-bold md:block">Start a reservation</a><button onClick={()=>setOpen(!open)} aria-label="Toggle menu" className="md:hidden">{open?<X/>:<Menu/>}</button></div><div className={`absolute inset-x-0 top-20 bg-[#171817] px-5 py-5 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${open?'pointer-events-auto translate-y-0 opacity-100':'pointer-events-none -translate-y-4 opacity-0'}`}>{links.map(([l,id],i)=><a onClick={()=>setOpen(false)} style={{transitionDelay:open?`${i*60}ms`:'0ms'}} className="block border-b border-white/10 py-4 transition-all" key={id} href={`#${id}`}>{l}</a>)}<a onClick={()=>setOpen(false)} className="mt-4 block rounded bg-brand p-4 text-center font-bold" href="#reserve">Start a reservation</a></div></nav>

    <section id="top" className="hero-grid relative flex min-h-screen items-center bg-[#171817] px-5 pb-20 pt-28 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_40%,rgba(212,66,45,.3),transparent_30%),linear-gradient(to_bottom,transparent,rgba(0,0,0,.4))]"/><div className="relative mx-auto grid w-full max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow flex items-center gap-2 text-[#f2a397]"><Sparkles size={14}/>Hospitality, beautifully organized</p><h1 className="max-w-3xl text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[82px]">Book your table in 30 seconds.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">Real time availability, instant confirmation, zero hassle. A calmer way to welcome every guest.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#reserve" className="rounded bg-brand px-6 py-4 font-bold">Reserve now</a><a href="#restaurants" className="rounded border border-white/40 px-6 py-4 font-bold">For restaurants</a></div></div><BookingMock/></div><a href="#product" aria-label="Scroll to product" className="absolute bottom-7 left-1/2 animate-bounce"><ChevronDown/></a></section>
    <section className="bg-cream"><div className="mx-auto grid max-w-7xl divide-y px-5 py-7 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[['47K+','reservations this month'],['1,200+','restaurant partners'],['98.7%','on time arrivals'],['24/7','always available']].map(x=><div className="p-5 text-center" key={x[1]}><b className="block text-3xl text-brand">{x[0]}</b><span className="text-xs text-muted">{x[1]}</span></div>)}</div></section>

    <section id="product" className="section"><Header tag="One thoughtful flow" title="A better table, from search to seated." copy="Guests get simplicity. Your team gets clarity. Everyone gets more time for hospitality."/><div className="grid gap-4 lg:grid-cols-12"><article className="bento bg-ink text-white lg:col-span-7 lg:row-span-2"><CalendarDays className="mb-16 text-[#f18b7c]"/><p className="eyebrow text-[#f18b7c]">Live availability</p><h3 className="text-3xl font-bold">The right table, right now.</h3><p className="mt-3 max-w-md text-white/60">Search by date, time, and party size while dining room capacity stays protected.</p><div className="mt-10 grid grid-cols-4 gap-2">{slots.slice(2,6).map((s,i)=><span className={`rounded border p-3 text-center text-sm ${i===1?'border-brand bg-brand':'border-white/15'}`} key={s}>{s}</span>)}</div></article><Bento icon={<MessageSquareText/>} title="Reminders that feel human" copy="Instant SMS confirmations and timely reminders keep every guest informed." className="bg-cream lg:col-span-5"/><Bento icon={<ShieldCheck/>} title="No overlaps" copy="Built in capacity protection." className="border lg:col-span-3"/><Bento icon={<BarChart3/>} title="Peak insights" copy="See demand clearly." className="bg-brand text-white lg:col-span-2"/></div></section>

    <section id="reserve" className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><Header tag="Book a table" title="Dinner plans, confirmed." copy="Choose an available time and leave your details. Your table is secured instantly."/><form onSubmit={submit} className="mt-8 space-y-4 rounded border bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><Field label="Your name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Guest name"/></Field><Field label="Phone number"><input required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="For confirmation"/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input required type="date" min={today} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Party size"><select value={form.partySize} onChange={e=>setForm({...form,partySize:e.target.value})}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></Field></div><fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-wider">Available time</legend><div className="grid grid-cols-3 gap-2">{slots.map(s=><button type="button" disabled={booked.has(s)} onClick={()=>setForm({...form,time:s})} key={s} className={`rounded border p-3 text-sm font-bold disabled:opacity-30 ${form.time===s?'border-brand bg-brand text-white':'bg-white'}`}>{s}</button>)}</div></fieldset><button disabled={loading||booked.has(form.time)} className="flex w-full items-center justify-center gap-2 rounded bg-brand p-4 font-bold text-white disabled:opacity-50">{loading?'Reserving…':'Confirm reservation'}<ArrowRight size={17}/></button>{message&&<p className="text-sm font-bold text-brand">{message}</p>}</form></div><Dashboard reservations={reservations} cancel={cancel}/></div></section>

    <section className="section"><div className="text-center"><Header tag="Simple for everyone" title="Three steps to your perfect table."/></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[[CalendarDays,'Select date and time','Browse current availability and choose your ideal slot.'],[Users,'Add party details','Share your name, phone, and party size.'],[Check,'Get confirmation','Your table is locked in and ready when you arrive.']].map(([Icon,t,c],i)=><article className="relative border-t pt-9" key={String(t)}><span className="absolute -top-4 grid size-8 place-items-center rounded-full bg-brand text-xs font-bold text-white">{i+1}</span><Icon className="mb-6 text-brand"/><h3 className="text-xl font-bold">{String(t)}</h3><p className="mt-3 text-sm leading-6 text-muted">{String(c)}</p></article>)}</div></section>

    <section id="stories" className="bg-ink py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1.3fr_.7fr] lg:px-8"><blockquote className="font-serif text-3xl leading-snug sm:text-5xl">“ReserveFlow cut our no show rate in half. The real time dashboard changed how we manage Friday nights.”<footer className="mt-8 font-sans text-sm text-white/50"><span className="mr-3 inline-grid size-10 place-items-center rounded-full bg-brand font-bold text-white">MG</span>Marco Giancini · General Manager, Osteria Blu</footer></blockquote><div className="space-y-5 border-l border-white/15 pl-8 text-lg italic text-white/75"><p>“Our guests love how fast booking is. Advance reservations grew by 35%.”</p><small className="not-italic text-white/40">Sarah Chen · Owner, Pacific Rim Kitchen</small><p className="pt-7">“Staff can manage everything from their phones. No more confusion.”</p><small className="not-italic text-white/40">David Rojas · Host, Casa Tinta</small></div></div></section>

    <section id="pricing" className="section"><div className="text-center"><Header tag="Simple, honest pricing" title="Choose the fit for your dining room."/></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{[['Starter','$49',['50 reservations monthly','Email support','Live dashboard','SMS confirmations']],['Professional','$129',['Unlimited reservations','Advanced analytics','Custom booking page','No show prevention']],['Enterprise','Custom',['Everything in Professional','API access','Dedicated onboarding','Service level agreement']]].map((p,i)=><article className={`relative rounded border p-8 ${i===1?'border-[3px] border-brand shadow-xl':''}`} key={p[0] as string}>{i===1&&<span className="absolute right-5 top-0 -translate-y-1/2 rounded bg-brand px-3 py-1 text-xs font-bold text-white">Most popular</span>}<h3 className="text-xl font-bold">{p[0]}</h3><p className="mt-7 text-4xl font-extrabold">{p[1]}<small className="text-sm font-normal text-muted">{i<2?' / month':''}</small></p><ul className="my-8 space-y-4">{(p[2] as string[]).map(x=><li className="flex gap-3 text-sm" key={x}><Check size={17} className="text-brand"/>{x}</li>)}</ul><a href="#reserve" className={`block rounded p-4 text-center text-sm font-bold ${i===1?'bg-brand text-white':'border'}`}>{i===2?'Talk to our team':'Choose plan'}</a></article>)}</div></section>

    <section className="bg-cream py-24"><div className="mx-auto max-w-3xl px-5"><div className="text-center"><Header tag="Questions, answered" title="The details before dinner."/></div><div className="mt-12 divide-y border-y">{faqs.map((f,i)=><div key={f[0]}><button onClick={()=>setFaq(faq===i?-1:i)} className="flex w-full items-center justify-between py-6 text-left font-bold">{f[0]}<ChevronDown className={faq===i?'rotate-180':''}/></button><div className={`grid transition-all ${faq===i?'grid-rows-[1fr] pb-6':'grid-rows-[0fr]'}`}><p className="overflow-hidden leading-7 text-muted">{f[1]}</p></div></div>)}</div></div></section>
    <section className="bg-brand px-5 py-24 text-center text-white"><h2 className="mx-auto max-w-3xl text-4xl font-extrabold tracking-tight sm:text-6xl">More guests. Fewer gaps. A calmer service.</h2><p className="mt-6 text-white/75">Give your team the reservation flow they deserve.</p><a href="#reserve" className="mt-9 inline-flex items-center gap-2 rounded bg-white px-6 py-4 font-bold text-ink">Reserve a table <ArrowRight size={18}/></a></section>
    <footer className="bg-[#171817] px-5 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 sm:flex-row"><div><Logo/><p className="mt-4 max-w-xs text-sm text-white/45">The modern reservation platform for restaurants that put hospitality first.</p></div><div className="flex flex-wrap gap-7 text-sm text-white/60">{links.map(([l,id])=><a key={id} href={`#${id}`}>{l}</a>)}<a href="#reserve">Book a table</a></div></div><p className="mx-auto mt-12 max-w-7xl border-t border-white/10 pt-6 text-xs text-white/35">© 2026 ReserveFlow. Built for better service.</p></footer>
  </main>
}

function Logo(){return <a href="#top" className="flex items-center gap-2 font-bold"><span className="grid size-8 place-items-center rounded bg-brand"><CalendarDays size={17}/></span>ReserveFlow</a>}
function Header({tag,title,copy}:{tag:string,title:string,copy?:string}){return <div className="mb-12 max-w-2xl"><p className="eyebrow">{tag}</p><h2 className="section-title">{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</div>}
function Bento({icon,title,copy,className}:{icon:React.ReactNode,title:string,copy:string,className:string}){return <article className={`bento ${className}`}><span className="mb-7 block text-brand">{icon}</span><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 opacity-65">{copy}</p></article>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field">{label}{children}</label>}
function BookingMock(){return <div className="mx-auto w-full max-w-lg rounded border border-white/15 bg-white/10 p-3 shadow-2xl backdrop-blur"><div className="rounded bg-white p-6 text-ink"><p className="eyebrow">Friday dinner</p><h3 className="text-xl font-bold">Find your table</h3><div className="mt-6 grid grid-cols-3 gap-2">{[['Date','Sep 25'],['Time','7:00 PM'],['Guests','2 people']].map(x=><div className="rounded border p-3 text-xs" key={x[0]}><span className="block text-muted">{x[0]}</span><b>{x[1]}</b></div>)}</div><p className="mb-3 mt-6 text-xs font-bold">Available times</p><div className="grid grid-cols-3 gap-2">{['6:30 PM','7:00 PM','7:30 PM','8:00 PM','8:30 PM','9:00 PM'].map((s,i)=><span className={`rounded border p-3 text-center text-sm font-bold ${i===1?'border-brand bg-brand text-white':''}`} key={s}>{s}</span>)}</div><p className="mt-6 flex items-center gap-2 border-t pt-5 text-xs text-muted"><ShieldCheck size={16} className="text-brand"/>Instant confirmation. No account required.</p></div></div>}
function Dashboard({reservations,cancel}:{reservations:Reservation[];cancel:(id:number)=>void}){return <div id="restaurants" className="rounded bg-ink p-6 text-white lg:p-8"><p className="eyebrow text-[#f18b7c]">Staff view</p><h3 className="text-2xl font-bold">Today’s reservations</h3><div className="mt-8 overflow-hidden rounded border border-white/10">{reservations.length===0?<p className="p-10 text-center text-sm text-white/50">New reservations will appear here in real time.</p>:reservations.slice(0,8).map(r=><div className="grid grid-cols-[60px_1fr_auto] items-center gap-3 border-b border-white/10 p-4" key={r.id}><b>{r.time}</b><div><p className="text-sm font-bold">{r.name} · {r.party_size} guests</p><p className="text-xs text-white/45">{r.date} · {r.status}</p></div>{r.status==='confirmed'&&<button onClick={()=>cancel(r.id)} aria-label={`Cancel reservation for ${r.name}`} className="p-2 text-white/50 hover:text-brand"><XCircle size={18}/></button>}</div>)}</div><div className="mt-8 grid grid-cols-6 items-end gap-2">{[28,48,75,92,68,42].map((h,i)=><div key={i}><div className="rounded-t bg-brand" style={{height:h}}/><small className="block text-center text-white/35">{17+i}</small></div>)}</div><p className="mt-3 text-xs text-white/45">Estimated capacity across dinner service</p></div>}
